#!/usr/bin/env bash

SSHKEY="$HOME/.ssh/id_rsa.pub"
USER="git"
HOST="192.168.1.138"
WHO=`whoami`
HOSTNAME=`hostname`
USERID="${1:-$WHO}@$HOSTNAME"
COMMAND="gitreceive upload-key $USERID"

#echo "cat $SSHKEY | ssh $USER@$HOST '"$COMMAND"'"
cat $SSHKEY | ssh $USER@$HOST "$COMMAND"
